CREATE DATABASE VEHICULOS

CREATE TABLE USUARIOS
(
IDUSUARIO INT IDENTITY (1,1),
CORREO VARCHAR (50),
CLAVE VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (30) NOT NULL,
APELLIDO VARCHAR (30) NOT NULL,
CONSTRAINT PK_IDUSUARIO PRIMARY KEY (IDUSUARIO),
CONSTRAINT UQ_UNIQUE UNIQUE (CORREO)
)
SELECT * FROM USUARIOS

INSERT INTO USUARIOS VALUES ('allan@upi.com', '1234', 'allan', 'morales')

create TABLE PLACA
(
IDPLACA INT IDENTITY,
NUMPLACA VARCHAR (6),
IDUSUARIO INT,
MONTO MONEY DEFAULT 0
CONSTRAINT PK_IDPLACA PRIMARY KEY (IDPLACA)
CONSTRAINT FK_IDUSUARIO1 FOREIGN KEY (IDPLACA)REFERENCES USUARIOS (IDUSUARIO)
)
SELECT * FROM PLACA
INSERT INTO PLACA VALUES ('123',1,200)

create TABLE REPORTES
 (
 idplaca int identity,
 nombre varchar (30) not null,
 apellido varchar (30) not null,
 numplaca varchar (6) not null,
 monto money default 0
 )
 INSERT INTO REPORTES VALUES ('ALLAN','MORALES','345',300)
 SELECT * FROM REPORTES
 SELECT * FROM placa P
INNER JOIN reportes R
ON P.IDPLACA = R.idplaca;









